minio:
  endpoint: http://localhost:9000
  accessKey: admin
  secretKey: wu82293382
  bucketName: blockchain


spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8001